apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apimanager
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-name: "API-Manager-UI"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.apimgr.ingressName }}
    secretName: tls-secret-manager
  rules:
  - host: {{ .Values.apimgr.ingressName }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.apimgr.name }}
          servicePort: {{ .Values.apimgr.trafficPort }}
        path: /