apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: apim-demo7
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: test@axwaycom
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
