apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.cassandra.name }}
  name: {{ .Values.cassandra.name }}
  namespace: {{ .Values.global.namespace | quote }}
spec:
  clusterIP: None
  ports:
    - name: cql
      port: {{ .Values.cassandra.portCql }}
      targetPort: {{ .Values.cassandra.portCql }}
{{- if eq .Values.cassandra.external false }}
  selector:
    app: {{ .Values.cassandra.name }}
{{- end }}
