# Headless service that allows us to get the IP addresses of our Cassandra nodes
{{- if eq .Values.cassandra.external false }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-peers
  name: cassandra-peers
  namespace: {{ .Values.global.namespace | quote }}
spec:
  clusterIP: None
  ports:
   - port: {{ .Values.cassandra.portIntraNode }}
     name: intra-node-communication
   - port: {{ .Values.cassandra.portTlsIntraNode }}
     name: tls-intra-node-communication
  selector:
   app: {{ .Values.cassandra.name }}
{{- end }}
