apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.cassandra.name }}
  name: {{ .Values.cassandra.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
{{- if eq .Values.cassandra.external false }}
  clusterIP: None
  ports:
    - name: cql
      port: {{ .Values.cassandra.portCql }}
      targetPort: {{ .Values.cassandra.portCql }}
  selector:
    app: {{ .Values.cassandra.name }}
{{- end }}
{{- if eq .Values.cassandra.external true }}
  type: ExternalName
  externalName: {{ .Values.cassandra.name }}{{ .Values.cassandra.domain }}
{{- end }}
