apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-certificate
spec:
  domains:
    - anm.axway-apim-on-gke.com
    - manager.axway-apim-on-gke.com
    - traffic.axway-apim-on-gke.com
    - portal.axway-apim-on-gke.com