{{- if eq .Values.mysqlAnalytics.enable true }}
{{- if eq .Values.mysqlAnalytics.external false }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    data: mysql-analytics
  name: mysql-analytics-pvc
  namespace: {{ .Values.global.namespace | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if eq .Values.platform "AZURE" }}
  storageClassName: managed-premium
  {{- end }}
  {{- if .Values.global.customStorageClass.scrwo }}
  storageClassName: {{ .Values.global.customStorageClass.scrwo }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mysqlAnalytics.quotaStorage }}Gi
{{- end }}
{{- end }}
