apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traffic
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - {{ .Values.apitraffic.apiManager.ingressName }}
    secretName: tls-secret-trafficManager
  rules:
  - host: {{ .Values.apitraffic.apiManager.ingressName }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.apitraffic.name }}
          servicePort: {{ .Values.apitraffic.portManager }}
        path: /
{{- if eq .Values.apitraffic.apiDefault.enabled true }}
  - hosts:
    - {{ .Values.apitraffic.apiDefault.ingressName }}
    secretName: tls-secret-trafficDefault
  rules:
  - host: {{ .Values.apitraffic.apiDefault.ingressName }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.apitraffic.name }}
          servicePort: {{ .Values.apitraffic.portGateway }}
        path: /
{{- end }}