{{- if .Values.amplifyTA.enabled }}

{{- if not (.Values.amplifyTA.existingSecretCert) }}
apiVersion: v1
kind: Secret
metadata:
   name: {{ template "traceabilityAgent.name" . }}-cert
data:
   private_key.pem: {{ required "Missing .Values.amplifyTA.config.privateKey" .Values.amplifyTA.config.privateKey | b64enc }}
   public_key.pem: {{ required "Missing .Values.amplifyTA.config.publicKey" .Values.amplifyTA.config.publicKey | b64enc }}
{{- end }}
---
{{- if not (.Values.amplifyTA.existingSecretCred) }}
apiVersion: v1
kind: Secret
metadata:
   name: {{ template "traceabilityAgent.name" . }}-cred
data:
   APIMANAGER_AUTH_PASSWORD: {{ required "Missing .Values.amplifyTA.apimanager.password" .Values.amplifyTA.apimanager.password | b64enc }}
   APIGATEWAY_AUTH_PASSWORD: {{ required "Missing .Values.amplifyTA.apigateway.password" .Values.amplifyTA.apigateway.password | b64enc }}
{{- end }}

{{- end }}