{{- if .Values.apitraffic.enabled -}}

{{- $imageTag := include "apitrafficImageTag" . -}}
{{- $imagePullPolicy := include "imagePullPolicy" . -}}
{{- $licenseSecret := include "licenseSecretName" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "apitraffic.name" . }}
  labels: {{- include "apitraffic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apitraffic.replicas }}
  selector:
    matchLabels:
      {{- include "apitraffic.selectorLabels" . | nindent 6 }}
  strategy:
{{ toYaml .Values.apitraffic.updateStrategy | indent 4 }}
  template:
    metadata:
      name: "{{ template "apitraffic.name" . }}"
      labels: 
        {{- include "apitraffic.selectorLabels" . | nindent 8 }}
      annotations:
        {{- range $key, $value := .Values.apitraffic.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
{{- if .Values.apitraffic.priorityClassName }}
      priorityClassName: {{ .Values.apitraffic.priorityClassName }}
{{- end }}
      securityContext:
{{ toYaml .Values.apitraffic.podSecurityContext | indent 8 }}
      {{- if .Values.apitraffic.serviceAccount }}
      serviceAccount: {{ .Values.apitraffic.serviceAccount }}
      {{- end }}
      {{- if .Values.apitraffic.hostAliases }}
      hostAliases: {{ toYaml .Values.apitraffic.hostAliases | nindent 6 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.apitraffic.terminationGracePeriod }}
      volumes:
        - name: events
{{- if .Values.pvcs.events.enabled }}
          persistentVolumeClaim:
            claimName: apigw-events
{{- else }}
          emptyDir: {}
{{- end }}
        - name: opentraffic
{{- if .Values.pvcs.opentraffic.enabled }}
          persistentVolumeClaim:
            claimName: apigw-opentraffic
{{- else }}
          emptyDir: {}
{{- end }}
        - name: trace
{{- if .Values.pvcs.trace.enabled }}
          persistentVolumeClaim:
            claimName: apigw-trace
{{- else }}
          emptyDir: {}
{{- end }}
        - name: audit
{{- if .Values.pvcs.audit.enabled }}
          persistentVolumeClaim:
            claimName: audit
{{- else }}
          emptyDir: {}
{{- end }}
{{- if $licenseSecret }}
        - name: license
          secret:
            secretName: {{ $licenseSecret }}
{{- end }}
      {{- if .Values.apitraffic.jvm.enabled }}
        - name: apitraffic-jvmxml
          configMap:
            name: {{ .Release.Name }}-jvmxml
            items:
              - key: apitraffic-jvmxml
                path: jvm.xml
      {{- end }}
      {{- range .Values.apitraffic.secretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
      {{- end }}
      {{- if .Values.apitraffic.extraVolumes }}
{{ toYaml ( .Values.apitraffic.extraVolumes ) | indent 8 }}
      {{- end }}
      {{- with .Values.apitraffic.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.apitraffic.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.apitraffic.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 8 }}
      {{- end }}
      initContainers:
      - name: init-cassandra
        image: busybox:1.33
        command: ['sh', '-c', 'until nc -w 3 -v {{ template "cassandra.name" . }} {{ .Values.cassandra.service.port }}; do echo waiting for cassandra-0; sleep 2; done;']
      {{- if .Values.mysqlmetrics.internal }}
      - name: init-mysql
        image: busybox:1.33
        command: ['sh', '-c', 'until nc -w 3 -v {{ template "mysqlmetrics.name" . }} {{ .Values.mysqlmetrics.primary.service.port }}; do echo waiting for mysql; sleep 2; done;']
      {{- end }}
      - name: init-anm
        image: busybox:1.33
        command: ['sh', '-c', 'until nc -w 3 -v {{ template "anm.name" . }} {{ .Values.anm.service.port }}; do echo waiting for anm; sleep 2; done;']
      {{- if .Values.apitraffic.extraInitContainers }}
{{ tpl .Values.apitraffic.extraInitContainers . | indent 6 }}
      {{- end }}
      containers:
      - name: "{{ template "apitraffic.name" . }}"
        securityContext:
{{ toYaml .Values.apitraffic.securityContext | indent 10 }}
      {{- if .Values.apitraffic.args }}
        args:
{{ toYaml .Values.apitraffic.args | indent 8 }}
      {{- end }}
      {{- if .Values.apitraffic.command }}
        command:
{{ toYaml .Values.apitraffic.command | indent 8 }}
      {{- end }}
        image: {{ .Values.global.dockerRepository }}/{{ .Values.apitraffic.image }}:{{ $imageTag }}
        imagePullPolicy: {{ $imagePullPolicy }}
        livenessProbe:
{{ toYaml .Values.apitraffic.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.apitraffic.readinessProbe | indent 10 }}
        ports:
        {{- range $key, $value := .Values.apitraffic.containerPorts }}
        - name: {{ $key }}
          containerPort: {{ $value }}
        {{- end }}
        {{- if .Values.apitraffic.extraPorts }}
{{- toYaml .Values.apitraffic.extraPorts | nindent 8 }}
        {{- end }}
        resources:
{{ toYaml .Values.apitraffic.resources | indent 10 }}
        env: 
        - name: EMT_ANM_HOSTS
        {{- if .Values.apitraffic.config.emtAnmHosts }}
          value: {{ .Values.apitraffic.config.emtAnmHosts | quote }}
        {{- else }}
          value: {{ template "anm.name" . }}:{{ required "Admin Node-Manager port is missing" .Values.anm.containerPorts.anm }}
        {{- end }}
        - name: EMT_DEPLOYMENT_ENABLED
          value: {{ default "false" .Values.apitraffic.config.emtDeploymentEnabled | quote }}
        - name: EMT_HEAP_SIZE_MB
          value: {{ default "1024" .Values.apitraffic.config.emtHeapSize | quote }}
        - name: EMT_TRACE_LEVEL
          value: {{ default "INFO" .Values.apitraffic.config.emtTraceLevel | quote }}
        - name: EMT_PARENT_HOST
          value: {{ default "api-gateway" .Values.apitraffic.config.emtParentHost | quote }}

        - name: CASS_HOST
          value: "{{ template "cassandra.name" . }}"
        - name: CASS_PORT
          value: {{ .Values.cassandra.service.port | quote }}
        - name: CASS_KEYSPACE
          value: {{ .Values.cassandra.cluster.keyspace }}
        - name: CASS_TKEYSPACE
          value: t_{{ .Values.cassandra.cluster.keyspace }}
        - name: CASS_USERNAME
          value: {{ .Values.cassandra.dbUser.user }}
        - name: CASS_PASS
        {{- if .Values.cassandra.dbUser.existingSecret }}
{{ toYaml .Values.cassandra.dbUser.existingSecret | indent 10 }}
        {{- else if .Values.cassandra.dbUser.password }}
          value: {{ .Values.cassandra.dbUser.password }}
        {{- else }}
          valueFrom:
            secretKeyRef:
              name: "{{ template "cassandra.name" . }}"
              key: "cassandra-password"
        {{- end }}
{{- if .Values.mysqlmetrics.internal }}
        - name: METRICS_DB_URL
          value: "jdbc:mysql://{{ template "mysqlmetrics.name" . }}:{{ .Values.mysqlmetrics.primary.service.port }}/{{ .Values.mysqlmetrics.auth.database }}?useSSL={{ .Values.mysqlmetrics.ssl }}"
        - name: METRICS_DB_USERNAME
          value: {{ .Values.mysqlmetrics.auth.username | quote }}
        - name: METRICS_DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ template "mysql.metrics.secretName" . }}
              key: mysql-password
{{- else if .Values.externalMetricsDB.env }}
{{ toYaml .Values.externalMetricsDB.env | nindent 8 }}
{{- end }}
        {{- if .Values.apitraffic.extraEnvs }}
{{ toYaml .Values.apitraffic.extraEnvs | indent 8 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.apitraffic.jvm.enabled }}
        - name: apitraffic-jvmxml
          mountPath: "/opt/Axway/apigateway/groups/emt-group/emt-service/conf/jvm.xml"
          subPath: jvm.xml
        {{- end }}
{{- if $licenseSecret }}
        - name: license
          mountPath: "/opt/Axway/apigateway/conf/licenses/lic.lic"
          subPath: license
{{- end }}
        - name: events
          mountPath: {{ default "/opt/Axway/apigateway/events" .Values.apitraffic.volumeMountsPaths.events | quote }}
        - name: opentraffic
          mountPath: {{ default "/opt/Axway/apigateway/logs/opentraffic" .Values.apitraffic.volumeMountsPaths.opentraffic | quote }}
        - name: trace
          mountPath: {{ default "/opt/Axway/apigateway/groups/emt-group/emt-service/trace" .Values.apitraffic.volumeMountsPaths.trace | quote }}
        {{- if .Values.apitraffic.extraVolumeMounts }}
{{ toYaml (.Values.apitraffic.extraVolumeMounts ) | indent 8 }}
        {{- end }}
        {{- if .Values.apitraffic.lifecycle }}
        lifecycle:
{{ toYaml .Values.apitraffic.lifecycle | indent 10 }}
        {{- end }}
        {{- if .Values.apitraffic.extraContainers }}
{{ toYaml .Values.apitraffic.extraContainers | indent 6 }}
        {{- end }}
{{- end }}