{{- if .Values.agents.discovery.enabled }}
{{- if not (.Values.agents.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
   name: {{ template "discoveryAgent.name" . }}
data:
   apimgr-auth-password: {{ .Values.agents.discovery.apimanager.password | b64enc }}
{{- if .Values.agents.central.privateKey  }}
   private_key.pem: {{ .Values.agents.central.privateKey | b64enc }}
{{- end }}
{{- if .Values.agents.central.publicKey  }}
   public_key.pem: {{ .Values.agents.central.publicKey | b64enc }}
{{- end }}

{{- end }}
{{- end }}