{{- if .Values.agents.discovery.enabled -}}

{{- $apimgrName := include "apimgr.name" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "discoveryAgent.name" . }}
  labels: {{- include "discoveryAgent.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.agents.discovery.deploymentAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.agents.discovery.replicas }}
  selector:
    matchLabels:
      {{- include "discoveryAgent.selectorLabels" . | nindent 6 }}
  strategy:
{{ toYaml .Values.agents.updateStrategy | indent 4 }}
  template:
    metadata:
      name: "{{ template "discoveryAgent.name" . }}"
      labels: 
        {{- include "discoveryAgent.selectorLabels" . | nindent 8 }}
      annotations:
        {{- range $key, $value := .Values.agents.discovery.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
{{- if .Values.agents.priorityClassName }}
      priorityClassName: {{ .Values.agents.priorityClassName }}
{{- end }}
      securityContext:
{{ toYaml .Values.agents.podSecurityContext | indent 8 }}
      {{- if .Values.agents.serviceAccount }}
      serviceAccount: {{ .Values.agents.serviceAccount }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.agents.discovery.terminationGracePeriod }}
      volumes:
      - name: agents-secret
        secret:
          secretName: {{ template "agentSecretName" . }}
        {{- range .Values.agents.discovery.secretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
        {{- end }}
        {{- if .Values.agents.discovery.extraVolumes }}
{{ toYaml ( .Values.agents.discovery.extraVolumes ) | indent 8 }}
        {{- end }}
      
      {{- with .Values.agents.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.agents.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.agents.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 6 }}
      {{- end }}
      initContainers:
      - name: init-apimgmt
        image: busybox:1.33
        command: ['sh', '-c', 'until nc -w 3 -v {{ template "apimgr.name" . }} 8075; do echo waiting for apimgr; sleep 2; done;']
        resources:
{{ toYaml .Values.agents.initResources | indent 10 }}
      {{- if .Values.agents.discovery.extraInitContainers }}
{{ tpl .Values.agents.discovery.extraInitContainers . | indent 6 }}
      {{- end }}
      containers:
      - name: "{{ template "discoveryAgent.name" . }}"
      {{- if .Values.agents.discovery.args }}
        args:
{{ toYaml .Values.agents.discovery.args | indent 8 }}
      {{- end }}
      {{- if .Values.agents.discovery.command }}
        command:
{{ toYaml .Values.agents.discovery.command | indent 8 }}
      {{- end }}
        securityContext:
{{ toYaml .Values.agents.securityContext | indent 10 }}
        image: {{ .Values.agents.dockerRepository }}/{{ .Values.agents.discovery.image }}:{{ .Values.agents.discovery.imageTag }}
        imagePullPolicy: {{ template "imagePullPolicy" . }}
        livenessProbe:
{{ toYaml .Values.agents.discovery.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.agents.discovery.readinessProbe | indent 10 }}
        ports:
        {{- range $key, $value := .Values.agents.discovery.containerPorts }}
        - name: {{ $key }}
          containerPort: {{ $value }}
        {{- end }}
        {{- if .Values.agents.discovery.extraPorts }}
{{- toYaml .Values.agents.discovery.extraPorts | nindent 8 }}
        {{- end }}
        resources:
{{ toYaml .Values.agents.discovery.resources | indent 10 }}
        env:
        - name: CENTRAL_AUTH_CLIENTID
          value: {{ required "Missing .Values.agents.central.clientId" .Values.agents.central.clientId | quote }}
        - name: CENTRAL_ORGANIZATIONID
          value: {{ required "Missing .Values.agents.central.organizationId" .Values.agents.central.organizationId | quote }}
        - name: CENTRAL_ENVIRONMENT
          value: {{ required "Missing .Values.agents.central.environment" .Values.agents.central.environment | quote }}
        - name: CENTRAL_AUTH_PRIVATEKEY
          value: {{ default "/opt/keys/private_key.pem" .Values.agents.central.privateKeyLocation | quote }}
        - name: CENTRAL_AUTH_PUBLICKEY
          value: {{ default "/opt/keys/public_key.pem" .Values.agents.central.publicKeyLocation | quote }}
        - name: CENTRAL_AGENTNAME
          value: {{ required "Missing .Values.agents.discovery.config.agentName" .Values.agents.discovery.config.agentName | quote }}
        - name: CENTRAL_APPENDENVIRONMENTTOTITLE
          value: {{ default "true" .Values.agents.discovery.config.appendEnvironmentToTitle | quote }}
        - name: CENTRAL_DEPLOYMENT
          value: {{ .Values.agents.central.deployment | quote }}
        - name: CENTRAL_URL
          value: {{ .Values.agents.central.url | quote }}
        - name: CENTRAL_PROXYURL
          value: {{ .Values.agents.central.proxyUrl | quote }}
        - name: CENTRAL_TEAM
          value: {{ .Values.agents.central.team | quote }}
        - name: CENTRAL_MODE
          value: {{ .Values.agents.central.mode | quote }}
        - name: CENTRAL_VERSIONCHECKER
          value: {{ .Values.agents.central.versionChecker | quote }}
          
        - name: APIMANAGER_HOST
          value: {{ default $apimgrName .Values.agents.apimanager.host | quote }}
        - name: APIMANAGER_PORT
          value: {{ default "8075" .Values.agents.apimanager.port | quote }}
        - name: APIMANAGER_AUTH_USERNAME
          value: {{ required "Missing .Values.agents.apimanager.username" .Values.agents.apimanager.username | quote }}
        - name: APIMANAGER_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "agentSecretName" . }}
              key: APIMANAGER_AUTH_PASSWORD
        - name: APIMANAGER_SSL_INSECURESKIPVERIFY
          value: {{ default "false" .Values.agents.apimanager.insecureSSL | quote }}
        - name: LOG_LEVEL
          value: {{ default "info" .Values.agents.discovery.config.logLevel | quote }}
        - name: LOG_OUTPUT
          value: {{ default "stdout" .Values.agents.discovery.config.logOutput | quote }}
        - name: LOG_FILE_PATH
          value: {{ default "logs" .Values.agents.discovery.config.logFilePath | quote }}
        - name: APIMANAGER_ALLOWAPPLICATIONAUTOCREATION
          value: {{ default "true" .Values.agents.discovery.config.allowApplicationAutoCreation | quote }}
        - name: CENTRAL_SUBSCRIPTIONS_APPROVAL_MODE
          value: {{ default "manual" .Values.agents.discovery.config.subscriptionsApprovalMode | quote }}
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_WEBHOOK_URL
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsWebhookUrl | quote }}
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_WEBHOOK_HEADERS
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsWebhookHeaders | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_APPROVAL_WEBHOOK_URL
          value: {{ .Values.agents.discovery.config.subscriptionsApprovalWebhookUrl | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_APPROVAL_WEBHOOK_HEADERS
          value: {{ .Values.agents.discovery.config.subscriptionsApprovalWebhookHeaders | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_APPROVAL_WEBHOOK_AUTHSECRET
          value: {{ .Values.agents.discovery.config.subscriptionsApprovalWebhookAuthSecret | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_HOST
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpHost | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_PORT
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpPort | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_AUTHTYPE
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpAuthType | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_USERNAME
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpUsername | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_PASSWORD
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpPassword | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_FROMADDRESS
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpFromAddress | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_SUBSCRIBE_SUBJECT
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpSubscribeSubject | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_SUBSCRIBE_BODY
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpSubscribeBody | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_SUBSCRIBE_OAUTH
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpSubscribeOAuth | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_SUBSCRIBE_APIKEYS
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpSubscribeAPIKeys | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_UNSUBSCRIBE_SUBJECT
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpUnsubscribeSubject | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_UNSUBSCRIBE_BODY
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpUnsubscribeBody | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_SUBSCRIBEFAILED_SUBJECT
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpSubscribeFailedSubject | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_SUBSCRIBEFAILED_BODY
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpSubscribeFailedBody | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_UNSUBSCRIBEFAILED_SUBJECT
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpUnsubscribeFailedSubject | quote }} 
        - name: CENTRAL_SUBSCRIPTIONS_NOTIFICATIONS_SMTP_UNSUBSCRIBEFAILED_BODY
          value: {{ .Values.agents.discovery.config.subscriptionsNotificationsSmtpUnsubscribeFailedBody | quote }} 
          
        {{- if .Values.agents.discovery.extraEnvs }}
{{ toYaml .Values.agents.discovery.extraEnvs | indent 8 }}
        {{- end }}
        {{- if .Values.agents.discovery.envFrom }}
        envFrom:
{{ toYaml .Values.agents.discovery.envFrom | indent 8 }}
        {{- end }}
        volumeMounts:
          - name: agents-secret
            mountPath: /opt/keys/private_key.pem
            subPath: private_key.pem
          - name: agents-secret
            mountPath: /opt/keys/public_key.pem
            subPath: public_key.pem
          {{- range .Values.agents.discovery.secretMounts }}
          - name: {{ .name }}
            mountPath: {{ .path }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
          {{- end }}
        {{- if .Values.agents.discovery.extraVolumeMounts }}
{{ toYaml (.Values.agents.discovery.extraVolumeMounts ) | indent 8 }}
        {{- end }}
        {{- if .Values.agents.discovery.lifecycle }}
        lifecycle:
{{ toYaml .Values.agents.discovery.lifecycle | indent 10 }}
        {{- end }}
        {{- if .Values.agents.discovery.extraContainers }}
{{ toYaml .Values.agents.discovery.extraContainers | indent 6 }}
        {{- end }}

{{- end }}