{{- if .Values.agents.traceability.enabled -}}

{{- $apimgrName := include "apimgr.name" . -}}
{{- $anmName := include "anm.name" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "traceabilityAgent.name" . }}
  labels: {{- include "traceabilityAgent.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.agents.traceability.deploymentAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.agents.traceability.replicas }}
  selector:
    matchLabels:
      {{- include "traceabilityAgent.selectorLabels" . | nindent 6 }}
  strategy:
{{ toYaml .Values.agents.updateStrategy | indent 4 }}
  template:
    metadata:
      name: "{{ template "traceabilityAgent.name" . }}"
      labels: 
        {{- include "traceabilityAgent.selectorLabels" . | nindent 8 }}
      annotations:
        {{- range $key, $value := .Values.agents.traceability.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
{{- if .Values.agents.priorityClassName }}
      priorityClassName: {{ .Values.agents.priorityClassName }}
{{- end }}
      securityContext:
{{ toYaml .Values.agents.podSecurityContext | indent 8 }}
      {{- if .Values.agents.serviceAccount }}
      serviceAccount: {{ .Values.agents.serviceAccount }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.agents.traceability.terminationGracePeriod }}
      volumes:
      - name: agents-secret
        secret:
          secretName: {{ template "agentSecretName" . }}
        {{- range .Values.agents.traceability.secretMounts }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName }}
        {{- end }}
        {{- if .Values.agents.traceability.extraVolumes }}
{{ toYaml ( .Values.agents.traceability.extraVolumes ) | indent 8 }}
        {{- end }}
      
      {{- with .Values.agents.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.agents.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.agents.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 6 }}
      {{- end }}
      initContainers:
      - name: init-apimgmt
        image: busybox:1.33
        command: ['sh', '-c', 'until nc -w 3 -v {{ template "apimgr.name" . }} 8075; do echo waiting for apimgr; sleep 2; done;']
        resources:
{{ toYaml .Values.agents.initResources | indent 10 }}
      {{- if .Values.agents.traceability.extraInitContainers }}
{{ tpl .Values.agents.traceability.extraInitContainers . | indent 6 }}
      {{- end }}
      containers:
      - name: "{{ template "traceabilityAgent.name" . }}"
      {{- if .Values.agents.traceability.args }}
        args:
{{ toYaml .Values.agents.traceability.args | indent 8 }}
      {{- end }}
      {{- if .Values.agents.traceability.command }}
        command:
{{ toYaml .Values.agents.traceability.command | indent 8 }}
      {{- end }}
        securityContext:
{{ toYaml .Values.agents.securityContext | indent 10 }}
        image: {{ .Values.agents.dockerRepository }}/{{ .Values.agents.traceability.image }}:{{ .Values.agents.traceability.imageTag }}
        imagePullPolicy: {{ template "imagePullPolicy" . }}
        livenessProbe:
{{ toYaml .Values.agents.traceability.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.agents.traceability.readinessProbe | indent 10 }}
        ports:
        {{- range $key, $value := .Values.agents.traceability.containerPorts }}
        - name: {{ $key }}
          containerPort: {{ $value }}
        {{- end }}
        {{- if .Values.agents.traceability.extraPorts }}
{{- toYaml .Values.agents.traceability.extraPorts | nindent 8 }}
        {{- end }}
        resources:
{{ toYaml .Values.agents.traceability.resources | indent 10 }}
        env:
        {{- if .Values.agents.traceability.extraEnvs }}
{{ toYaml .Values.agents.traceability.extraEnvs | indent 8 }}
        {{- end }}
        {{- if .Values.agents.traceability.envFrom }}
        envFrom:
{{ toYaml .Values.agents.traceability.envFrom | indent 8 }}
        {{- end }}
        volumeMounts:
          - name: agents-secret
            mountPath: /opt/keys/private_key.pem
            subPath: private_key.pem
          - name: agents-secret
            mountPath: /opt/keys/public_key.pem
            subPath: public_key.pem
          {{- range .Values.agents.traceability.secretMounts }}
          - name: {{ .name }}
            mountPath: {{ .path }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
          {{- end }}
        {{- if .Values.agents.traceability.extraVolumeMounts }}
{{ toYaml (.Values.agents.traceability.extraVolumeMounts ) | indent 8 }}
        {{- end }}
        {{- if .Values.agents.traceability.lifecycle }}
        lifecycle:
{{ toYaml .Values.agents.traceability.lifecycle | indent 10 }}
        {{- end }}
        {{- if .Values.agents.traceability.extraContainers }}
{{ toYaml .Values.agents.traceability.extraContainers | indent 6 }}
        {{- end }}

{{- end }}