# Default values for apimgr-ext-cass.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


global:
   # AZURE, OPENSHIFT, MINIKUBE
   platform: ""
   # Define is managed service must be used for specific cloud provider. Doesn't work for Openshift and minikube.
   managedIngress: false

   #Annotation

   pullPolicy: Always
   initImageTag: "busybox:1.33"
   updateStrategy: "RollingUpdate"
   editor: "Axway"
   apimVersion: "7.7-20210330"
   domainName: ""
   dockerRegistry:
      secret: "registry-secret"
      url: "axwayproductsdemo.azurecr.io"
      username: "apim-demo"
      token: "WXLOkIcYitqJZGiKJ65wqBydlM+klvM8"
   nodeAffinity:
      enable: false
      dbName: "apimpool"
      apimName: "apimpool"
   enableDynamicLicense: false
   emtDeployment: "true"
   customStorageClass:
      scrwo:
      scrwm:
   createSecrets: true
   issuedByLetsEncrypt: false
   bodySize: 10m
   volumes:
      accessModes: ReadWriteOnce
      gateway:
         paths:
            logs: "/opt/Axway/apigateway/groups/emt-group/emt-service/logs"
            trace: "/opt/Axway/apigateway/groups/emt-group/emt-service/trace"
      nodemanager:
         paths:
            events: "/opt/Axway/apigateway/events"
            logs: "/opt/Axway/apigateway/logs"
            trace: "/opt/Axway/apigateway/trace"
   jvm:
      gateway:
         enable: false
      nodemanager:
         enable: false
   userID: 1000
   probe:
      page: "/healtchecklb"


anm:
   name: anm
   buildTag: "20210330"
   imageName: "apim-anm-7.7"
   ingressName: "anm"
   replicaCount: 1
   pvcQuota: 1
   trafficPort: 8090
   trafficPortUI: 8091
   logTraceToFile: "true"
   logTraceJSONtoSTDOUT: "false"
   emt_heap_size_mb: "1024"
   emt_topology_log_enabled: "true"
   emt_topology_ttl: 10
   emt_trace_level: "INFO"
   certInSecret: false
   volumes:
      quota: 1Gi
      name: "anm-pvc"

apimgr:
   name: apimgr
   buildTag: "20210330"
   imageName: "apim-gtw-7.7"
   ingressName: "api-mgr"
   replicaCount: 1
   trafficPort: 8075
   logTraceToFile: "true"
   logTraceJSONtoSTDOUT: "false"
   logOpenTrafficOutput: "stdout"
   emt_heap_size_mb: "1024"
   emt_topology_log_enabled: "true"
   emt_topology_ttl: 10
   emt_trace_level: "INFO"
   certInSecret: false
   volumes:
      quota: 1Gi
      name: "apimgr-pvc"
   sso:
      enable: false

apitraffic:
   name: traffic
   buildTag: "20210330"
   imageName: "apim-gtw-7.7"
   ingressName: "api"
   portManager: 8065
   portGateway: 8080
   portGatewaySSL: 8081
   replicaCount: 1
   autoscaling:
      enable: false
      maxReplicas: 3
      averageUtilization: 70
   logTraceToFile: "true"
   logTraceJSONtoSTDOUT: "false"
   logOpenTrafficOutput: "stdout"
   emt_trace_level: "INFO"
   emt_heap_size_mb: "1512"
   emt_topology_log_enabled: "true"
   emt_topology_ttl: 10
   volumes:
      quota: 1Gi
      name: "traffic-pvc"
   certInSecret: false
   probe:
      port: 8065
      scheme: "HTTPS"

apiportal:
   enable: false
   name: "api-portal"
   buildTag: "7.7-20210330"
   imageName: "apim-ptl"
   ingressName: "apiportal"
   trafficPort: 443
   scheme: HTTPS
   ssl: 1
   configureManager: 1
   replicaCount: 1
   share:
      secret: "apiportal-secret-name"
      name: "apiportal-volume-rwm-name"
   certInSecret: false
   runAsUser: 1000
   sso:
      enable: false

apiaga:
   enable: false
   name: apiaga
   buildTag: "20210330"
   imageName: "apim-aga-7.7"
   ingressName: "analytics"
   replicaCount: 1
   trafficPort: 8040
   logTraceToFile: "true"
   logTraceJSONtoSTDOUT: "false"
   logOpenTrafficOutput: "stdout"
   emt_heap_size_mb: "1024"
   emt_topology_ttl: 10
   emt_trace_level: "INFO"
   certInSecret: false

# Disclaimers:
# Axway does not support MySQL in Containers.
mysqlAnalytics:
   enable: true
   external: false
   host: "externalUri"
   name: mysql-aga
   ssl: false
   imageName: "mysql"
   buildTag: "5.7.26"
   replicaCount: 1
   dbName: "analytics"
   adminUser: "report"
   adminPasswd: "changeme"
   rootPasswd: "changeme"
   quotaStorage: 10
   port: 3306

# Disclaimers:
# Axway does not support Cassandra in Containers.
# The latest supported buildTag for Cassandra is 2.2.12.
cassandra:
   external: false
   name: "cassandra"
   adminName: "cassandra"
   adminPasswd: "changeme"
   portCql: 9042
   portJmx: 7199
   portIntraNode: 7000
   portTlsIntraNode: 7001
   buildTag: "3.11.11"
   registry: "bitnami/cassandra"
   replicaCount: 1
   clusterName: "cassandra"
   keyspace: "apim_demo_1"
   host1: "ip_host1"
   host2: "ip_host2"
   host3: "ip_host3"
   domain: ""
   consistency_level: "LOCAL_QUORUM"

# Disclaimers:
# Axway does not support MySQL in Containers.
mysqlPortal:
   external: true
   name: "mysql-portal"
   imageName: "mysql"
   buildTag: "5.7.26"
   replicaCount: 1
   dbName: "portal"
   adminUser: "portal"
   adminPasswd: "changeme"
   quotaStorage: 10
   port: 3306

oauth:
   enable: false
   name: "oauth"
   ingressName: "oauth"
   trafficPort: 8089
   certInSecret: false
