# Values for sandbox environment.

global:
   # AZURE, OPENSHIFT, MINIKUBE
   # MINIKUBE is the one more in-line for local tests.
   platform: "MINIKUBE"

   #Annotation

   # That is just a dummy domain.
   domainName: "axway.io"
   # To have the local-path storage class, remember to run:
   # kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
   customStorageClass:
      scrwo: hostpath
      scrwm: hostpath
   enableDynamicLicense: false
   pullPolicy: IfNotPresent
   dockerRegistry:
      url: docker-registry.demo.axway.com/apim-demo
   jvm:
      gateway:
         enable: true
      nodemanager:
         enable: true
   dashboard: true
   probe:
      page: "/healthcheck"


anm:
   buildTag: "7.7.20210830-01"
   imageName: "anm-demo"
   trafficPortUI: 8090
   logTraceJSONtoSTDOUT: "true"
   emt_heap_size_mb: "2048"

apimgr:
   buildTag: "7.7.20210830-01"
   imageName: "apimgt-demo"
   logTraceJSONtoSTDOUT: "true"

apitraffic:
   buildTag: "7.7.20210830-01"
   imageName: "apimgt-demo"
   probe:
     port: 8080
     scheme: "HTTP"

apiaga:
   enable: false
   buildTag: "7.7.20210830-01"
   imageName: "apigw-analytics-demo"

mysqlAnalytics:
   enable: false

cassandra:
   external: false
   # Change this IP to the Cassandra's cluster IPs.
   host1: "10.42.12.229"
   host2: "10.42.12.229"
   host3: "10.42.12.229"
   # That is the default domain for Cassandra on the default namespace.
   # Change it to your specific case if necessary.
   domain: ".default.svc.cluster.local"

apiportal:
   enable: false
   buildTag: "7.7.20210830-01"
   imageName: "apiportal"
   trafficPort: 80
   scheme: HTTP
   runAsUser: 1048