{{- if and .Values.apiportal.enabled .Values.apiportal.config.ssl.generateCertificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "certificates.name" . }}
  labels:
    app: "{{ template "apiportal.name" . }}"
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "apiportal.gen-certs" . ) | indent 2 }}
{{- end }}