{{- if eq .Values.global.createSecrets true }}
apiVersion: v1
kind: Secret
metadata:
  name: apim-password
type: Opaque
data:
  dbmysqlanalytics: {{ .Values.mysqlanalytics.adminPasswd | b64enc }}
  dbmysqlroot: {{ .Values.mysqlanalytics.rootPasswd | b64enc }}
  dbmysqlportal: {{ .Values.mysqlportal.adminPasswd | b64enc }}
  dbcass: {{ .Values.cassandra.dbUser.password | b64enc }}
{{- end }}