{{- if and .Values.filebeat.enabled .Values.filebeat.filebeatSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "filebeat.name" . }}-secret
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  {{- if .Values.filebeat.filebeatSecrets.beatsSystemUsername }}
  BEATS_SYSTEM_USERNAME: {{ .Values.filebeat.filebeatSecrets.beatsSystemUsername | b64enc | quote }}
  {{- else }}
  BEATS_SYSTEM_USERNAME: ""
  {{- end }}
  {{- if .Values.filebeat.filebeatSecrets.beatsSystemPassword }}
  BEATS_SYSTEM_PASSWORD: {{ .Values.filebeat.filebeatSecrets.beatsSystemPassword | b64enc | quote }}
  {{- else }}
  BEATS_SYSTEM_PASSWORD: ""
  {{- end }}
{{- end }}