{{- if and (.Values.filebeat.enabled) (not .Values.filebeat.elasticsearchCaSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "filebeat.name" . }}-cert
  labels:
    app: "{{ template "filebeat.name" . }}"
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  ca.crt: {{ .Values.filebeat.elasticSearchCa | quote }}
{{- end }}