{{- if or .Values.anm.jvm.enabled .Values.apimgr.jvm.enabled .Values.apitraffic.jvm.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
   name: {{ .Release.Name }}-jvmxml
   namespace: {{ .Release.Namespace | quote }}
data:
{{- if .Values.anm.jvm.enabled }}
    anm-jvmxml: |
{{ .Values.anm.jvm.config | indent 6 }}
{{- end -}}

{{- if .Values.apimgr.jvm.enabled }}
    apimgr-jvmxml: |
{{ .Values.apimgr.jvm.config | indent 6 }}
{{- end -}}

{{- if .Values.apitraffic.jvm.enabled }}
    apitraffic-jvmxml: |
{{ .Values.apitraffic.jvm.config | indent 6 }}
{{- end -}}

{{- end }}