apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.apitraffic.share.name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
     storage: {{ .Values.apitraffic.share.quota }}Gi
  azureFile:
    secretName: {{ .Values.apitraffic.share.secret | quote }}
    shareName: {{ .Values.apitraffic.share.name | quote }}
    readOnly: false
  mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
