{{- if .Values.apitraffic.autoscaling.enable }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ .Values.apitraffic.name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.apitraffic.name }}
  minReplicas: {{ .Values.apitraffic.replicaCount }}
  maxReplicas: {{ .Values.apitraffic.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.apitraffic.autoscaling.averageUtilization }}
{{- end }}