apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apigw-events
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if eq .Values.global.platform "AZURE" }}
  storageClassName: azurefile-premium
  {{- end }}
  {{- if .Values.global.customStorageClass.scrwm }}
  storageClassName: {{ .Values.global.customStorageClass.scrwm }}
  {{- end }}
  resources:
    requests:
      {{- if eq .Values.global.platform "AZURE" }}
      storage: 100Gi
      {{- else }}
      storage: {{ .Values.apitraffic.share.quota }}Gi
      {{- end }}
