apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: traffic
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- if eq .Values.platform "AZURE" }}
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-protocol: https
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: http01
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- if eq .Values.platform "ESX" }}
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.apitraffic.ingressName }}
    secretName: tls-secret-traffic
  rules:
  - host: {{ .Values.apitraffic.ingressName }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.apitraffic.name }}
          servicePort: {{ .Values.apitraffic.portManager }}
        path: /
