{{- if eq .Values.global.platform "OPENSHIFT" }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.apitraffic.name }}
spec:
  to:
    kind: Service
    name: {{ .Values.apitraffic.name }}
  port:
    targetPort: {{ .Values.apitraffic.portManager }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  {{- end }}