apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-box
  namespace: apim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy-box
  template:
    metadata:
      labels:
        app: busy-box
    spec:
      containers:
        - name: busy-box
          image: busybox:1.33
          command: [ "sh", "-c", "tail -f /dev/null" ]