apiVersion: v2

appVersion: 7.7-20210330

version: 7.7-20210330

description: Package for demo instance of Axway AMPLIFY API Management.
icon: https://images.app.goo.gl/MbQyRo2M2jzAsed79
home: https://github.com/Axway/Cloud-Automation/tree/master/APIM/Helmchart
keywords:
- API Management, Axway, AMPLIFY API, Demo, Azure
maintainers:
- email: ncomandini@axway.com
  name: cloud-automation community
- email: cwiechmann@axway.com
  name: cloud-automation community
name: axway-apim

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - name: cassandra
    alias: cassandra
    repository: https://charts.bitnami.com/bitnami
    version: 7.7.3 # Installs Cassandra 3.11.11
    condition: cassandra.internal
  - name: mysql
    alias: mysqlmetrics
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami/mysql
    version: 8.x.x
    condition: mysqlmetrics.internal
  - name: mysql
    alias: mysqlapiportal
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami/mysql
    version: 8.x.x
    condition: mysqlapiportal.internal