{{- if eq .Values.oauth.enabled true }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apimanager
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - {{ .Values.oauth.ingressName }}
    secretName: tls-secret-oauth
  rules:
  - host: {{ .Values.oauth.ingressName }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.oauth.name }}
          servicePort: {{ .Values.oauth.trafficPort }}
        path: /
{{- end }}