apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.anm.name | quote }}
  name: {{ .Values.anm.name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
spec:
  clusterIP: None
  ports:
  - name: gatewaymanager
    port: {{ .Values.anm.trafficPort }} 
    targetPort: {{ .Values.anm.trafficPort }}
    protocol: TCP
  - name: gatewaymanagerui
    port: {{ .Values.anm.trafficPortUI }}
    targetPort: {{ .Values.anm.trafficPortUI }}
    protocol: TCP
  selector:
    app: {{ .Values.anm.name | quote }}
  sessionAffinity: ClientIP
  type: ClusterIP
