{{- if eq .Values.oauth.enable true }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.oauth.name | quote }}
  name: {{ .Values.oauth.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.oauth.trafficPort }}
    targetPort: {{ .Values.oauth.trafficPort }}
    protocol: TCP
  selector:
    app: {{ .Values.apitraffic.name | quote }}
  sessionAffinity: ClientIP
  type: ClusterIP
status:
  loadBalancer: {}
{{- end }}
