{{- if eq .Values.oauth.enable true }}
{{- if ne .Values.global.platform "OPENSHIFT" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oauth
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.global.managedIngress }}
    {{- if eq .Values.global.platform "AZURE" }}
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-protocol: https
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    cert-manager.io/cluster-issuer: azure-dns-issuer
    {{- end }}
    {{- else }}
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.oauth.ingressName }}.{{ .Values.global.domainName }}
    secretName: apioauth-ingress-cert
  rules:
  - host: {{ .Values.oauth.ingressName }}.{{ .Values.global.domainName }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.oauth.name }}
          servicePort: {{ .Values.oauth.trafficPort }}
        path: /
{{- end }}
{{- end }}
