{{- if eq .Values.apiportal.enable true }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    data: mysql-portal
  name: mysql-portal-pvc
  namespace: {{ .Values.global.namespace | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if eq .Values.platform "AZURE" }}
  storageClassName: managed-premium
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mysqlPortal.quotaStorage }}Gi
{{- end }}