{{- if eq .Values.apiportal.enable true }}
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.mysqlPortal.name }}
  name: {{ .Values.mysqlPortal.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.mysqlPortal.port }}
    targetPort: {{ .Values.mysqlPortal.port }}
    protocol: TCP
  selector:
    app: {{ .Values.mysqlPortal.name }}
  clusterIP: None
{{- end }}