apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.apimgr.name | quote }}
  name: {{ .Values.apimgr.name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.apimgr.trafficPort }}
    targetPort: {{ .Values.apimgr.trafficPort }} 
    protocol: TCP
  selector:
    app: {{ .Values.apimgr.name | quote }}
  sessionAffinity: ClientIP
  type: ClusterIP
status:
  loadBalancer: {}
