apiVersion: v1
kind: Secret
metadata:
  name: apim-password
type: Opaque
data:
  dbmysqlanalytics: {{ .Values.cassandra.userpasswd }}
  dbmysqlroot: {{ .Values.mysqlAnalytics.adminPasswd }}
  dbmysqlportal: {{ .Values.mysqlPortal.adminPasswd }}
  dbcass: {{ .Values.cassandra.userpasswd }}