{{- if eq .Values.global.createSecrets true }}
apiVersion: v1
kind: Secret
metadata:
  name: apim-password
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  dbmysqlanalytics: {{ .Values.mysqlAnalytics.adminPasswd | b64enc }}
  dbmysqlroot: {{ .Values.mysqlAnalytics.rootPasswd | b64enc }}
  dbmysqlportal: {{ .Values.mysqlPortal.adminPasswd | b64enc }}
  dbcass: {{ .Values.cassandra.adminPasswd | b64enc }}
{{- end }}