apiVersion: v1
kind: Secret
metadata:
  name: apim-password
type: Opaque
data:
  dbmysqlanalytics: {{ .Values.cassandra.userpasswd | b64enc }}
  dbmysqlroot: {{ .Values.mysqlAnalytics.adminPasswd | b64enc }}
  dbmysqlportal: {{ .Values.mysqlPortal.adminPasswd | b64enc }}
  dbcass: {{ .Values.cassandra.userpasswd | b64enc }}