apiVersion: v1
kind: ConfigMap
metadata:
   name: jvmxml
   namespace: {{ .Release.Namespace | quote }}
data:
   jvm: |
    <ConfigurationFragment>
    <VMArg name="-Ddont.expect.100.continue=true"/>
    <VMArg name="-Dio.swagger.parser.util.RemoteUrl.trustAll=true"/>
    <VMArg name="-Dio.swagger.v3.parser.util.RemoteUrl.trustAll=true"/>
    </ConfigurationFragment>