{{- if eq .Values.global.enableDynamicLicense true }}
apiVersion: v1
kind: ConfigMap
metadata:
   name: license
   namespace: {{ .Release.Namespace | quote }}
data:
   license:
{{ .Files.Get "files/license.lic" | toYaml | indent 8 }}
{{- end }}