apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.dockerRegistry.secret }}
  namespace: {{ .Values.global.namespace | quote }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson