{{- if eq .Values.global.createSecrets true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.dockerRegistry.secret }}
  namespace: {{ .Release.Namespace | quote }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
{{- end }}