name: Release Axway APIM Helm-Chart

on:
  release:
    types: [published]
    # Tags used to release the APIM-Helm-Chart
    # e.g. apim-helm-chart-0.0.1
    tags:
      - '*apim-helm*'

jobs:
  release-helm-chart:
    defaults:
      run:
        working-directory: 'APIM/Helmchart/amplify-apim-7.7'
    name: Release Axway-APIM Helm chart
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "Get version number from Release-Tag: ${{ github.event.release.tag_name }}"
        echo RELEASE_VERSION=`"${{ github.event.release.tag_name }}" | gawk 'match($0, /.*-([0-9]\.[0-9]\.[0-9][-A-Za-z]*)/, matches) {print matches[1]}'``
        echo "Release version is: $RELEASE_VERSION"
        echo $RELEASE_VERSION >> $GITHUB_ENV
    - name: Create packaged Helm-Chart
      run: |
        pwd
        helm package . --dependency-update --app-version ${{ env.RELEASE_VERSION }} --version ${{ env.RELEASE_VERSION }}
    - name: upload-helm-chart
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: axway-apim-${{ env.RELEASE_VERSION }}.tgz
        asset_name: helm-chart-axway-apim-${{ env.RELEASE_VERSION }}.tgz
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}