name: Release Axway APIM Helm-Chart

on:
  release:
    types: [published]
    # Tags used to release the APIM-Helm-Chart
    # e.g. apim-helm-chart-0.0.1
    tags:
      - '*apim-helm*'

jobs:
  release-helm-chart:
    defaults:
      run:
        working-directory: 'APIM/Helmchart'
    name: Release Axway-APIM Helm chart
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "Get version number from Release-Tag: ${{ github.event.release.tag_name }}"
        RELEASE_VERSION=`echo "${{ github.event.release.tag_name }}" | gawk 'match($0, /.*([0-9]\.[0-9]\.[0-9][-A-Za-z]*)/, matches) {print matches[1]}'`
        echo "Release version is: $RELEASE_VERSION"
        echo RELEASE_VERSION=$RELEASE_VERSION >> $GITHUB_ENV
    - name: Set version number
      run: |
        yq -i '.version="${{ env.RELEASE_VERSION }}"' ./Chart.yaml
        echo "Set version: ${RELEASE_VERSION} in AWS-EKS Example Readme."
        sed -E -i 's/(apim-helm)-[0-9].*\.[0-9].*\.[0-9].*/\1-${{ env.RELEASE_VERSION }}/' ./examples/aws-eks/README.md
        sed -E -i 's/(helm-chart-axway-apim)-[0-9].*\.[0-9].*\.[0-9].*(\.tgz)/\1-${{ env.RELEASE_VERSION }}\2/' ./examples/aws-eks/README.md
        echo "Set version: ${{ env.RELEASE_VERSION }} in Azure Example Readme."
        sed -E -i 's/(apim-helm)-[0-9].*\.[0-9].*\.[0-9].*/\1-${{ env.RELEASE_VERSION }}/' ./examples/azure-aks/README.md
        sed -E -i 's/(helm-chart-axway-apim)-[0-9].*\.[0-9].*\.[0-9].*(\.tgz)/\1-${{ env.RELEASE_VERSION }}\2/' ./examples/azure-aks/README.md
        cat ./Chart.yaml
    - name: Create packaged Helm-Chart
      run: |
        pwd
        helm package . --dependency-update --app-version ${{ env.RELEASE_VERSION }} --version ${{ env.RELEASE_VERSION }} --destination /tmp
    - name: upload-helm-chart
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: /tmp/axway-apim-${{ env.RELEASE_VERSION }}.tgz
        asset_name: helm-chart-axway-apim-${{ env.RELEASE_VERSION }}.tgz
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update repository
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Helm-Chart ${{ env.RELEASE_VERSION }} released'