name: Test Google-GKE Examples

env:
  exampleValuesFiles1: examples/google-gke/google-gke-example-values.yaml

on:
  push:
    branches:
      - master
    paths:
      - APIM/Helmchart/**

jobs:
  test-aws-eks:
    name: Test Google-GKE Examples
    defaults:
      run:
        working-directory: 'APIM/Helmchart'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Example 1
      run: helm template --validate test -f ${{ env.exampleValuesFiles1 }} . --debug