name: Test AWS-EKS Examples

env:
  exampleValuesFiles1: examples/aws-eks/aws-eks-example-values.yaml

on:
  push:
    branches:
      - master
    paths:
      - APIM/Helmchart/**

jobs:
  test-aws-eks:
    name: Test AWS-EKS Example
    defaults:
      run:
        working-directory: 'APIM/Helmchart'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Example 1
      run: helm template --validate test -f ${{ env.exampleValuesFiles1 }} . --debug