name: Test Azure-AKS Examples

env:
  exampleValuesFiles1: examples/azure-aks/azure-aks-example-agic-value.yaml
  exampleValuesFiles2: examples/azure-aks/azure-aks-example-noingress-values.yaml

on:
  push:
    branches:
      - master
    paths:
      - APIM/Helmchart/**

jobs:
  test-aws-eks:
    name: Test Azure-AKS Examples
    defaults:
      run:
        working-directory: 'APIM/Helmchart'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Example 1
      run: helm template --validate test -f ${{ env.exampleValuesFiles1 }} . --debug
    - name: Test Example 2
      run: helm template --validate test -f ${{ env.exampleValuesFiles2 }} . --debug